### ISSUE TITLE
Exact match option

### ISSUE THREAD

**Issue by alemagio** [mcollina/help-me#2]
I found that if the doc directory contains 2 files where one file has the name entirely contained in the other filename it is not possible (for what I could understand) to match the first one:

doc: hello.txt, hello-world.txt

It is not possible to get hello.txt

I opened a PR with a test and a possible fix creating a boolean option which, if true, makes it match exactly the entire file name so `hello` will only match `hello.txt` and `hello-world` will only match `hello-world.txt`.

**Comment by mcollina** [comment]
How about sorting the file names by length first? I _think_ that should solve it.

**Comment by alemagio** [comment]
I think that sorting `files` by name should fix the problem if we also take the first result.
See [here](https://github.com/mcollina/help-me/blob/b9c2ab3623a1f0cef11e02228ce8a45ad1f35e60/help-me.js#L53), I believe (correct me if I'm missing something off course) that if we sort files we still get into this `if` statement.

What do you think?

**Comment by mcollina** [comment]
I agree. Then we should do a pass on the filter array to see if there is an exact match, and if so use that doc file.

**Comment by alemagio** [comment]
Sounds good to me.
I'm going to push an update asap
Thanks

**Comment by alemagio** [comment]
PR updated
