### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by khattakdev** [mcollina/help-me#8]
The current example  ( `example.js` ) needs some modification in order to execute it successfully. I think it should be a ready-made example without any modification required.
Currently, if you try to execute it, you get the following error

![image](https://user-images.githubusercontent.com/37709578/122554571-9cb5fc00-d052-11eb-81d0-d57a69b1dd71.png)

With very little modification, this could be fixed.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by khattakdev** [comment]
> Would you like to send a Pull Request to address this issue?

Yep, sending in a while
